import type { Certificate, Organization } from "./types";

/**
 * PLACEHOLDER registry. The organisations below are invented — none is a real
 * institution — and every certificate is a sample. Replace them with the
 * client's real records, ideally in the Studio (Mijozlar va sertifikatlar):
 * the site switches to the CMS copy as soon as one organisation is published.
 */
export const organizations: Organization[] = [
  { slug: "barqaror-moliya-bank", name: "Barqaror Moliya Bank", sector: "bank", city: { uz: "Toshkent", ru: "Ташкент" }, since: 2015 },
  { slug: "oqsaroy-invest-bank", name: "Oqsaroy Invest Bank", sector: "bank", city: { uz: "Toshkent", ru: "Ташкент" }, since: 2017 },
  { slug: "nurafshon-lizing", name: "Nurafshon Lizing", sector: "leasing", city: { uz: "Toshkent", ru: "Ташкент" }, since: 2018 },
  { slug: "chorsu-mikromoliya", name: "Chorsu Mikromoliya", sector: "microfinance", city: { uz: "Toshkent", ru: "Ташкент" }, since: 2019 },
  { slug: "bargoh-takaful", name: "Bargoh Takaful", sector: "takaful", city: { uz: "Toshkent", ru: "Ташкент" }, since: 2020 },
  { slug: "zarafshon-halol-invest", name: "Zarafshon Halol Invest", sector: "investment", city: { uz: "Samarqand", ru: "Самарканд" }, since: 2021 },
  { slug: "yangi-vodiy-bank", name: "Yangi Vodiy Bank", sector: "bank", city: { uz: "Fargʻona", ru: "Фергана" }, since: 2021 },
  { slug: "sahro-agro-lizing", name: "Sahro Agro Lizing", sector: "leasing", city: { uz: "Buxoro", ru: "Бухара" }, since: 2022 },
  { slug: "afshona-food", name: "Afshona Food", sector: "business", city: { uz: "Buxoro", ru: "Бухара" }, since: 2022 },
  { slug: "sipoh-takaful", name: "Sipoh Takaful", sector: "takaful", city: { uz: "Toshkent", ru: "Ташкент" }, since: 2023 },
  { slug: "minor-halol-savdo", name: "Minor Halol Savdo", sector: "business", city: { uz: "Toshkent", ru: "Ташкент" }, since: 2023 },
  { slug: "ilm-moliya-mikrokredit", name: "Ilm Moliya Mikrokredit", sector: "microfinance", city: { uz: "Namangan", ru: "Наманган" }, since: 2024 },
];

const AAOIFI = "AAOIFI SS";

export const certificates: Certificate[] = [
  {
    number: "MK-2026-0148",
    org: "barqaror-moliya-bank",
    kind: "product",
    subject: { uz: "“Halol Avto” ijara asosidagi avtomobil moliyalashtirish", ru: "«Халяль Авто» — автофинансирование на основе иджары" },
    standards: [`${AAOIFI} 9`, `${AAOIFI} 5`],
    issued: "2026-07-22",
    validUntil: "2027-07-21",
  },
  {
    number: "MK-2026-0141",
    org: "zarafshon-halol-invest",
    kind: "sukuk",
    subject: { uz: "Ijara sukuk emissiyasi, 1-seriya", ru: "Выпуск иджара-сукук, серия 1" },
    standards: [`${AAOIFI} 17`, `${AAOIFI} 9`],
    issued: "2026-06-03",
    validUntil: "2031-06-02",
  },
  {
    number: "MK-2026-0133",
    org: "bargoh-takaful",
    kind: "operations",
    subject: { uz: "Oilaviy takaful faoliyati", ru: "Деятельность семейного такафула" },
    standards: [`${AAOIFI} 26`, "IFSB-8"],
    issued: "2026-04-15",
    validUntil: "2027-04-14",
  },
  {
    number: "MK-2026-0127",
    org: "oqsaroy-invest-bank",
    kind: "product",
    subject: { uz: "Murobaha asosidagi savdo moliyalashtirish", ru: "Торговое финансирование на основе мурабахи" },
    standards: [`${AAOIFI} 8`],
    issued: "2026-03-02",
    validUntil: "2027-03-01",
  },
  {
    number: "MK-2026-0119",
    org: "sipoh-takaful",
    kind: "operations",
    subject: { uz: "Umumiy takaful faoliyati", ru: "Деятельность общего такафула" },
    standards: [`${AAOIFI} 26`],
    issued: "2026-02-10",
    validUntil: "2027-02-09",
  },
  {
    number: "MK-2026-0112",
    org: "ilm-moliya-mikrokredit",
    kind: "product",
    subject: { uz: "Qarzi hasan asosidagi taʼlim krediti", ru: "Образовательное финансирование на основе карз хасан" },
    standards: [`${AAOIFI} 19`],
    issued: "2026-01-19",
    validUntil: "2027-01-18",
  },
  {
    number: "MK-2025-0098",
    org: "minor-halol-savdo",
    kind: "operations",
    subject: { uz: "Ulgurji savdo va toʻlov muddatini kechiktirish amaliyoti", ru: "Оптовая торговля и отсрочка платежа" },
    standards: [`${AAOIFI} 8`, `${AAOIFI} 2`],
    issued: "2025-11-24",
    validUntil: "2026-11-23",
  },
  {
    number: "MK-2025-0091",
    org: "yangi-vodiy-bank",
    kind: "product",
    subject: { uz: "Mudoraba omonat hisobi", ru: "Депозитный счёт мудараба" },
    standards: [`${AAOIFI} 13`],
    issued: "2025-10-06",
    validUntil: "2026-10-05",
  },
  {
    number: "MK-2025-0084",
    org: "sahro-agro-lizing",
    kind: "product",
    subject: { uz: "Qishloq xoʻjaligi texnikasi ijarasi", ru: "Лизинг сельхозтехники" },
    standards: [`${AAOIFI} 9`],
    issued: "2025-08-18",
    validUntil: "2026-08-17",
  },
  {
    number: "MK-2025-0077",
    org: "zarafshon-halol-invest",
    kind: "fund",
    subject: { uz: "“Zarafshon Halol” aksiyalar fondi", ru: "Фонд акций «Зарафшан Халяль»" },
    standards: [`${AAOIFI} 21`, `${AAOIFI} 12`],
    issued: "2025-07-01",
    validUntil: "2026-12-31",
  },
  {
    number: "MK-2025-0069",
    org: "afshona-food",
    kind: "operations",
    subject: { uz: "Xomashyoni salam asosida xarid qilish", ru: "Закупка сырья на основе салам" },
    standards: [`${AAOIFI} 10`],
    issued: "2025-05-12",
    validUntil: "2026-05-11",
  },
  {
    number: "MK-2025-0055",
    org: "nurafshon-lizing",
    kind: "operations",
    subject: { uz: "Ijara muntahiya bittamlik faoliyati", ru: "Деятельность иджара мунтахия биттамлик" },
    standards: [`${AAOIFI} 9`],
    issued: "2025-03-20",
    validUntil: "2026-03-19",
    revoked: true,
  },
  {
    number: "MK-2025-0041",
    org: "chorsu-mikromoliya",
    kind: "product",
    subject: { uz: "Kichik biznes uchun murobaha mikromoliyasi", ru: "Микрофинансирование мурабаха для малого бизнеса" },
    standards: [`${AAOIFI} 8`],
    issued: "2025-02-03",
    validUntil: "2027-02-02",
  },
  {
    number: "MK-2024-0036",
    org: "barqaror-moliya-bank",
    kind: "operations",
    subject: { uz: "Islom oynasi faoliyati", ru: "Деятельность исламского окна" },
    standards: [`${AAOIFI} 1`, `${AAOIFI} 8`, `${AAOIFI} 9`],
    issued: "2024-12-09",
    validUntil: "2026-12-08",
  },
  {
    number: "MK-2024-0022",
    org: "oqsaroy-invest-bank",
    kind: "product",
    subject: { uz: "Mushoraka asosidagi ipoteka", ru: "Ипотека на основе мушараки" },
    standards: [`${AAOIFI} 12`],
    issued: "2024-06-17",
    validUntil: "2025-06-16",
  },
  {
    number: "MK-2024-0014",
    org: "nurafshon-lizing",
    kind: "product",
    subject: { uz: "Uskuna ijarasi", ru: "Лизинг оборудования" },
    standards: [`${AAOIFI} 9`],
    issued: "2024-03-04",
    validUntil: "2025-03-03",
  },
];
